### PR TITLE
update npm command for windows

### LINKED ISSUE #32: Windows support
Currently this module fails to install packages on windows because of the issue mentioned in http://stackoverflow.com/questions/37125619/spawnsyncnpm-install-gives-error-spawnsync-npm-enoent

cc @scott113341

### PR DESCRIPTION
**Pull request by debopamsengupta**
fixes #32

### CODE REVIEW

**Comment by debopamsengupta** [comment]
cc @scott113341 :)

**Comment by matteofigus** [comment]
Good work @debopamsengupta - I used [this](https://github.com/IndigoUnited/node-cross-spawn) in some other projects, I think it includes some fixes for that specific problem as well. In any case, I think it is better to merge this and see if it's enough for making requirey green on Windows, so that we can then include it in other projects.

**Comment by scott113341** [comment]
Great, thank you for the PR @debopamsengupta!

**Comment by scott113341** [comment]
Released in `6.0.2`

**Comment by debopamsengupta** [comment]
brilliant, thanks @scott113341 :)

**Pull request merged**
